name: Ping Hugging Face Spaces (daily)

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at 00:00 UTC (05:30 IST)
  workflow_dispatch:        # Allows manual trigger

jobs:
  ping-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Spaces
        run: |
          set -euo pipefail

          SPACES=(
            "Kenox786/YoutubeHindi"
            "Kenox786/XsmartBot"
          )

          for SPACE in "${SPACES[@]}"; do
            echo "=== Pinging: https://huggingface.co/spaces/$SPACE ==="
            for i in {1..3}; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
                -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
                "https://huggingface.co/spaces/$SPACE")
              
              echo "Attempt $i: HTTP $STATUS"
              if [ "$STATUS" -eq 200 ]; then
                echo "✅ Success for $SPACE"
                break
              else
                echo "⚠️ Failed (HTTP $STATUS), retrying..."
                sleep 5
              fi
            done
          done
