name: Ping Hugging Face Spaces (daily)

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  ping-spaces:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Spaces
        run: |
          set -euo pipefail
          SPACES=(
            "Kenox786/YoutubeHindi"
            "Kenox786/XsmartBot"
          )

          for space in "${SPACES[@]}"; do
            echo "=== Pinging: https://huggingface.co/spaces/$space ==="
            for i in {1..3}; do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
                -H "Authorization: Bearer $HF_TOKEN" \
                "https://huggingface.co/spaces/$space")
              echo "Attempt $i: HTTP $STATUS"
              if [ "$STATUS" -eq 200 ]; then
                echo "✅ Success: $space"
                break
              else
                echo "⚠️ Failed (HTTP $STATUS), retrying..."
                sleep 5
              fi
            done
          done
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
