name: Keep Hugging Face Spaces Active

on:
  schedule:
    # Run every 24 hours (daily at midnight UTC)
    # This ensures spaces stay active well within the 48-hour limit
    - cron: '0 0 * * *'  # Every 24 hours (daily at midnight UTC)
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Keep Spaces Active
      run: |
        # Add your Hugging Face Space URLs here
        # IMPORTANT: Use the deployed app URLs (.hf.space), NOT the repository URLs
        SPACES=(
          "https://Kenox786-XsmartBot.hf.space"
          "https://Kenox786-YoutubeHindi.hf.space"
          # Add more spaces as needed
        )
        
        echo "Starting keep-alive pings..."
        
        for space in "${SPACES[@]}"
        do
          echo "Pinging: $space"
          
          # Make HTTP request to keep space active
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            --max-time 30 \
            --retry 2 \
            --retry-delay 5 \
            "$space" || echo "000")
          
          if [ "$response" = "200" ]; then
            echo "✅ Success: $space (HTTP $response)"
          elif [ "$response" = "000" ]; then
            echo "⚠️  Timeout/Error: $space"
          else
            echo "⚠️  Warning: $space (HTTP $response)"
          fi
          
          # Wait 10 seconds between requests to be respectful
          sleep 10
        done
        
        echo "Keep-alive pings completed!"
    
    - name: Log completion
      run: |
        echo "Workflow completed at $(date)"
        echo "Next run scheduled in 24 hours (daily at midnight UTC / 5:30 AM IST)"
